[tool.poetry]
name = "strava-metrics"
version = "0.1.0"
description = ""
authors = ["Robert Duffy"]
license = "Y"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.1"
numpy = "^1.26.4"
ipywidgets = "^8.1.2"
requests = "^2.31.0"
polars = "^0.20.16"
jupyter = "^1.0.0"
notebook = "^7.1.2"
ipydatagrid = "^1.2.1"
ipykernel = "^6.29.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
